undo "fix typo"
This change causes errors like this (tested on meteor 1.3 beta 12):

```
index.jsx:142Uncaught TypeError: (0 , _reactKomposer.composeWithTracker) is not a function
```